import { IMAGE_CONSTANTS } from '@constants/imageConstants';

export const SIGNUP_CONSTANTS = {
  IMAGES: {
    LOGO: IMAGE_CONSTANTS.LOGO,
    CHARACTER: IMAGE_CONSTANTS.NOMALCHARACTER,
    BACKWARD: IMAGE_CONSTANTS.BACKWARD,
  },
  INPUT_IMAGE: {
    CHECK: IMAGE_CONSTANTS.CHECK,
    ERROR: IMAGE_CONSTANTS.ERROR,
    VECTOR: IMAGE_CONSTANTS.VECTOR,
    EYESON: IMAGE_CONSTANTS.EYESON,
    EYESOFF: IMAGE_CONSTANTS.EYESOFF,
    UP: IMAGE_CONSTANTS.UP,
  },
};
